name: drift_sounds
version: 0.0.1
description: "A library for storing `flutter_audio_games` sounds in a drift sqlite database."
homepage: https://github.com/chrisnorman7/drift_sounds

environment:
  sdk: ^3.10.2
  flutter: ">=1.17.0"

dependencies:
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  drift_sounds_database: ^0.1.0
  flutter:
    sdk: flutter
  flutter_audio_games: ^0.51.7
  flutter_soloud: ^3.4.8
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
