name: database_sounds
version: 0.0.1
description: "A library for storing sounds in a database. Backed by `flutter_audio_games` and `drift`."
homepage: https://github.com/chrisnorman7/database_sounds

environment:
  sdk: ^3.11.0-200.1.beta
  flutter: ">=1.17.0"

dependencies:
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  flutter:
    sdk: flutter
  flutter_audio_games: ^0.50.1
  flutter_soloud: ^3.4.6
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.10.4
  drift_dev: ^2.30.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

scripts:
  watch: dart run build_runner watch -d
  build: dart run build_runner build -d
